### ISSUE TITLE
doesnt work on mac

### ISSUE THREAD

**Issue by insanity54** [insanity54/hostr#1]
getting this error:

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/chrisgrimmett/scripts/hostr/hostr:189:28)
    at IncomingMessage.emit (events.js:107:17)
    at IncomingMessage.Readable.read (_stream_readable.js:373:10)
    at flow (_stream_readable.js:750:26)
    at resume_ (_stream_readable.js:730:3)
    at _stream_readable.js:717:7
    at process._tickCallback (node.js:355:11)
```

**Comment by insanity54** [comment]
f2ddbede02b7839b02a864a7db1c557bd0002e2b fixes
